- id: '1532802208787'
  alias: Fukt notis
  trigger:
  - at: 07:00
    platform: time
  - at: '10:00'
    platform: time
  - at: '13:00'
    platform: time
  - at: '16:00'
    platform: time
  - at: '20:00'
    platform: time
  - at: '17:00'
    platform: time
  - at: '21:00'
    platform: time
  condition: []
  action:
  - data:
      message: fukt i källaren {{ states.sensor.kallaretemp_2_0.state }} %
    service: notify.telegram_jocke
- id: b0bcc474eecf4b468d2238aac24afe14
  alias: Telegram-Bot Fukt
  trigger:
  - event_data:
      command: /fukt
    event_type: telegram_command
    platform: event
  action:
  - data_template:
      message: Nuvarande Fukt i källaren, {{ states.sensor.kallaretemp_2_0.state }}%
      target: '{{ trigger.event.data.user_id }}'
    service: telegram_bot.send_message
- id: '1532810540535'
  alias: 'Hög Fukt '
  trigger:
  - entity_id: sensor.kallaretemp_2_0
    platform: state
    to: '70'
  condition: []
  action:
  - data:
      message: Hög fukt i källaren
    service: notify.telegram_jocke
- id: '1533575039523'
  alias: God natt
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - data:
      message: Då säger vi God Natt nu. Den stora lampan har gått ner. Tempen ligger
        på {{states.sensor.kallaretemp_2_1.state }} & Fukten på {{ states.sensor.kallaretemp_2_0.state
        }} %
    service: notify.telegram_jocke
- id: '1534701090394'
  alias: Strömavbrott
  trigger:
  - entity_id: sensor.nut_ups_status_data
    from: OL
    platform: state
    to: OB
  condition: []
  action:
  - data:
      message: Strömavbrott på villa moga !
    service: notify.telegram_jocke
  - data:
      message: Strömavbrott på villa moga !
    service: notify.telegram_helena
- id: '1534701155450'
  alias: Strömmen Tillbaka
  trigger:
  - entity_id: sensor.nut_ups_status_data
    from: OB
    platform: state
    to: OL
  condition: []
  action:
  - data:
      message: 'Strömmen är tillbaka '
    service: notify.telegram_jocke
- id: '1534910062529'
  alias: Telegram-Bot Miljö
  trigger:
  - event_data:
      command: /klimat
    event_type: telegram_command
    platform: event
  condition: []
  action:
  - data:
      message: 'Fukt Och temperatur i källaren,  {{ states.sensor.kallaretemp_2_0.state
        }} %, {{states.sensor.kallaretemp_2_1.state}} °, Fukt och temperatur vardagsrum,
        {{states.sensor.vardagsrumtemp_8_0.state}} %, {{states.sensor.vardagsrumtemp_8_1.state
        }} ° '
    service: telegram_bot.send_message
- id: '1537032941882'
  alias: Offline.Boot
  trigger:
  - entity_id: binary_sensor.onlinesensor
    for:
      minutes: 20
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      message: internet goes down
    service: notify.telegram_jocke
  - data:
      entity_id: switch.router
    service: switch.turn_off
  - delay: 00:05:00
  - data:
      entity_id: switch.router
    service: switch.turn_on
  - delay: 00:05:00
  - data:
      message: Startat om
    service: notify.telegram_jocke
- id: '1537035541825'
  alias: Online
  trigger:
  - entity_id: binary_sensor.onlinesensor
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: 'Internet is back '
    service: notify.telegram_jocke
- id: '1540800424119'
  alias: Rörelse
  trigger:
  - entity_id: binary_sensor.rorelse_grovkok_2
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: Rörelse Detekterad
    service: notify.telegram_jocke
- id: '1547900104231'
  alias: Solnedgång
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - data:
      entity_id:
      - light.lampan_pa_hornan
      - light.gasthus_gavel1
    service: light.turn_on
- id: '1547926991599'
  alias: Ytterbelysning av
  trigger:
  - at: '23:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: group.belysningute
    service: light.turn_off
- id: '1550302826462'
  alias: home-switch
  trigger:
  - event_data:
      event: 1002
      id: sw1
    event_type: deconz_event
    platform: event
  condition: []
  action:
  - data:
      message: Testar knapp, 1
    service: notify.telegram_jocke
  - alias: ''
    data:
      entity_id: input_boolean.status
    service: input_boolean.turn_on
- id: '1550304793706'
  alias: away-switch
  trigger:
  - event_data:
      event: 2002
      id: sw1
    event_type: deconz_event
    platform: event
  condition: []
  action:
  - data:
      message: Testar knapp, 2
    service: notify.telegram_jocke
  - data:
      entity_id: input_boolean.status
    service: input_boolean.turn_off

