- id: '1532802208787'
  alias: Fukt notis
  trigger:
  - at: 07:00
    platform: time
  - at: '10:00'
    platform: time
  - at: '13:00'
    platform: time
  - at: '16:00'
    platform: time
  - at: '20:00'
    platform: time
  - at: '17:00'
    platform: time
  - at: '21:00'
    platform: time
  condition: []
  action:
  - data:
      message: fukt i källaren {{ states.sensor.kallaretemp_2_0.state }} %
    service: notify.telegram_jocke
- alias: telegram bot that replies the temprature
  trigger:
  - platform: event
    event_type: telegram_command
    event_data:
      command: /fukt
  action:
  - service: telegram_bot.send_message
    data_template:
      target: '{{ trigger.event.data.user_id }}'
      message: Nuvarande Fukt i källaren, {{ states.sensor.kallaretemp_2_0.state }}%
  id: b0bcc474eecf4b468d2238aac24afe14
- id: '1532810540535'
  alias: 'Hög Fukt '
  trigger:
  - entity_id: sensor.kallaretemp_2_0
    platform: state
    to: '70'
  condition: []
  action:
  - data:
      message: Hög fukt i källaren
    service: notify.telegram_jocke
- id: '1533575039523'
  alias: God natt
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - data:
      message: Då säger vi God Natt nu. Den stora lampan har gått ner. Tempen ligger
        på {{states.sensor.kallaretemp_2_1.state }} & Fukten på {{ states.sensor.kallaretemp_2_0.state
        }} %
    service: notify.telegram_jocke
- id: '1534701090394'
  alias: Strömavbrott
  trigger:
  - entity_id: sensor.nut_ups_status_data
    from: Online
    platform: state
    to: Offline
  condition: []
  action:
  - data:
      message: Strömavbrott
    service: notify.telegram_jocke
- id: '1534701155450'
  alias: Strömmen Tillbaka
  trigger:
  - entity_id: sensor.nut_ups_status_data
    from: Offline
    platform: state
    to: Online
  condition: []
  action:
  - data:
      message: 'Strömmen är tillbaka '
    service: notify.telegram_jocke
