homeassistant:
  # Name of the location where Home Assistant is running
  name: Villa-Moga
  # Location required to calculate the time the sun rises and sets
  latitude: 59.910568
  longitude: 18.051643
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_named packages
# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:
ios:
http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr
    monitored_conditions:
      - temperature
      - symbol
      - humidity
  - platform: nut
    username: nut
    password: nut
    resources:
      - ups.load
      - ups.status
      - input.voltage
      - battery.runtime
      - ups.mfr
  - platform: mqtt
    name: 'Söder'
    state_topic: "/Temperatur/soder/Temperature"
    retain: true
    icon: mdi:temperature-celsius
  - platform: mqtt
    name: 'Norr'
    state_topic: "/Temperatur/Norr/Temperature"
    retain: true
    icon: mdi:temperature-celsius

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

panel_iframe:
  mdiindex:
    title: MDI Icon Index
    icon: mdi:vector-square
    url: https://cdn.rawgit.com/james-fry/home-assistant-mdi/efd95d7a/home-assistant-mdi.html
mysensors:
  gateways:
    - device: '/dev/ttyUSB0'
      persistence_file: '/home/homeassistant/.homeassistant/mysensors.json'
      baud_rate: 115200



binary_sensor:
  - platform: ping
    host: 8.8.8.8
    count: 2
    scan_interval: 600
    name: online-sensor
  - platform: uptimerobot
    api_key: !secret uptime_key

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api
    allowed_chat_ids:
      - !secret telegram_jocke
      - !secret telegram_helena
notify:
  - name: Telegram_Jocke
    platform: telegram
    chat_id: !secret telegram_jocke
  - name: Telegram_Helena
    platform: telegram
    chat_id: !secret telegram_helena

switch:
  - platform: broadlink
    host: 192.168.0.85
    type: rm_mini
    mac: '34:EA:34:43:93:04'
    timeout: 15
    switches:
      aircon_living_room:
        friendly_name: "Living Room AC"
        command_on: 'JgCSAAABJ5MWNhYRFhIWNRYSFhEWEhYSFjUWEhYRFjYWERYSFhIWERYSFhEWEhYRFhIWNRcRFhIWERYSFhEWEhY1FxEWNRcRFhIWNRYSFgACkBcRFhIWERYSFhEWEhYRFxEWERcRFhIWERYSFjUWEhYRFxEWEhYRFhIWERYSFhEXERYRFxEWEhYRFhIWNRY2FjUXAA0FAAAAAAAA'
        command_off: 'JgBMAm05DSoOKQ40DBAMDwwrDQ8MEA4pDCsMEAwrDg4MDw4pDSsMD'


#deconz:
#  host: 192.168.0.190
#  port: 8080



#climate: !include climate.yaml
#  - platform: broadlink
#    name: Toyotomi Akira
#    host: 192.168.0.85
#    mac: '34:EA:34:43:93:04'
#    ircodes_ini: '/custom_components/broadlink_climate_codes/toyotomi_akira.ini'
#    min_temp: 16
#    max_temp: 30
#    target_temp: 20
#    target_temp_step: 1
#    temp_sensor: sensor.living_room_temperature
#    default_operation: 'off'
#    default_fan_mode: mid
#    customize:
#      operations:
#        - 'off'
#        - cool
#        - heat
#      fan_modes:
#        - low
#        - mid
#        - high
#        - auto


logger:
  default: info
  logs:
    pydeconz: debug
    homeassistant.components.deconz: debug
mqtt:
  password: testar
