################################################################################
# Temperatur.nu rapport                                                        #
# Made By: Joakim Engberg                                                      #
# Source:                                                                      #
# https://github.com/joaeng/backuphome/blob/master/packages/leave.yaml         #
################################################################################

################################################################################
#                                                                configuration #
################################################################################



################################################################################
#                                                                        Group #
################################################################################

group:

################################################################################
#                                                                       switch #
################################################################################

#switch:

################################################################################
#                                                                      sensors #
################################################################################

sensor:

################################################################################
#                                                                  Automations #
################################################################################

automation:
  - alias: Tempertur_nu
    hide_entity: false
    initial_state: true
    trigger: 
      platform: time
      minutes: "/5"
    action:
      service: shell_command.temperatur_nu
#      entity_id: script.away




################################################################################
#                                                                       script #
################################################################################

script:
shell_command:
  temperatur_nu: "/usr/bin/curl http://www.temperatur.nu/rapportera.php?hash=aa9bedf480b50c1c65bbabf479e9c3a4&t={{ states.sensor.utomhustemperatur.state }}"
